name: Continuous Delivery

on:
  push:
    branches: [main, staging]

env:
  NODE_VERSION: "18.x"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"

      - name: Install dependencies
        run: "yarn install"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ghcr.io/reservoirprotocol/relayer:latest
            ghcr.io/reservoirprotocol/relayer:${{ github.sha }}

  deploy-dev:
    name: Deploy to Development
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [build]
    environment: dev
    if: github.ref == 'refs/heads/staging'
    steps:
      - name: Checkout repository k8s-configs
        uses: actions/checkout@v3
        with:
          repository: unevenlabs/k8s-configs
          token: ${{ secrets.DEVOPSBOT_TOKEN }}
          path: k8s-configs

      - name: Deploy to Dev Environment
        working-directory: k8s-configs
        run: |
          ./utils/version_update.sh \
            ./dev/platform/relayer-sepolia.yaml \
            ${{ github.sha }} \
            relayer-sepolia

  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [build]
    environment: prod
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository k8s-configs
        uses: actions/checkout@v3
        with:
          repository: unevenlabs/k8s-configs
          token: ${{ secrets.DEVOPSBOT_TOKEN }}
          path: k8s-configs

      - name: Deploy to Prod Environment
        working-directory: k8s-configs
        run: |
          ./utils/version_update.sh \
            ./prod/platform/relayer.yaml \
            ${{ github.sha }} \
            relayer
          ./utils/version_update.sh \
            ./prod/platform/relayer-arbitrum.yaml \
            ${{ github.sha }} \
            relayer-arbitrum
          ./utils/version_update.sh \
            ./prod/platform/relayer-polygon.yaml \
            ${{ github.sha }} \
            relayer-polygon
          ./utils/version_update.sh \
            ./prod/platform/relayer-realtime.yaml \
            ${{ github.sha }} \
            relayer-realtime
          ./utils/version_update.sh \
            ./prod/platform/relayer-optimism.yaml \
            ${{ github.sha }} \
            relayer-optimism
          ./utils/version_update.sh \
            ./prod/platform/relayer-arbitrum-nova.yaml \
            ${{ github.sha }} \
            relayer-arbitrum-nova
          ./utils/version_update.sh \
            ./prod/platform/relayer-avalanche.yaml \
            ${{ github.sha }} \
            relayer-avalanche
          ./utils/version_update.sh \
            ./prod/platform/relayer-mumbai.yaml \
            ${{ github.sha }} \
            relayer-mumbai
          ./utils/version_update.sh \
            ./prod/platform/relayer-base.yaml \
            ${{ github.sha }} \
            relayer-base
          ./utils/version_update.sh \
            ./prod/platform/relayer-zora.yaml \
            ${{ github.sha }} \
            relayer-zora
          ./utils/version_update.sh \
            ./prod/platform/relayer-sepolia.yaml \
            ${{ github.sha }} \
            relayer-sepolia
          ./utils/version_update.sh \
            ./prod/platform/relayer-base-goerli.yaml \
            ${{ github.sha }} \
            relayer-base-goerli
          ./utils/version_update.sh \
            ./prod/platform/relayer-zora-testnet.yaml \
            ${{ github.sha }} \
            relayer-zora-testnet
